Commit testing changes

diff --git a/targets/gentoo/snapshot/type/dead b/targets/gentoo/snapshot/type/dead
--- a/targets/gentoo/snapshot/type/dead
+++ b/targets/gentoo/snapshot/type/dead
@@ -5,7 +5,8 @@ if [ "$[snapshot/source/type]" = "git" ]
 then
 	git archive --prefix=portage/ "$[snapshot/source/branch:lax]" > $tarout || die "Couldn't create tar archive"
 else
-	rsync -a --delete --exclude /packages/ --exclude /distfiles/ --exclude /local/ --exclude CVS/ --exclude /.git/ "$[rsync/path:lax]/" "$[path/work]/portage/" || die "Couldn't sync portage tree"
+	die
+	rsync -a --delete --exclude /packages/ --exclude /distfiles/ --exclude /local/ --exclude CVS/ --exclude /.git/ --include /usr/local/gentoo-keywords/ "$[rsync/path:lax]/" "$[path/work]/portage/" || die "Couldn't sync portage tree"
 	tar -c -C $[path/work] portage > $tarout || die "Couldn't create tar archive"
 fi
 ]
